version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # Menjamo port da ne bi smetao postojećem MySQL-u

  web:
    build: .
    restart: always
    env_file: .env
    ports:
      - "5001:5000"  # Isto menjamo port da ne smeta tvojoj aplikaciji
    depends_on:
      - db

volumes:
  db_data:

